name: 'ArgoCD Diff'
description: 'Diffs all ArgoCD apps in the repo, and provides the diff as a PR comment'
author: 'Quizlet'
inputs:
  argocd-server-url: 
    description: ArgoCD server url (without the protocol)
    required: true
  argocd-token: 
    description: ArgoCD token for a local or project-scoped user https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15
    required: true
  argocd-version: 
    description: ArgoCD Version
    default: v1.6.1
    required: false
  github-token: 
    description: Github Token
    required: true
  argocd-extra-cli-args: 
    description: Extra arguments to pass to the argocd CLI
    default: --grpc-web
    required: false
  insecure:
    description: Do not verify TLS certificate authority
    default: "false"
    required: false
  concurrency:
    description: No. of concurrent runs
    default: "20"
    required: false
  retry-count:
    description: No. of retries in case of unsuccessfull argocd diffs
    default: "1"
    required: false
  retry-delay:
    description: Delay before retry argocd diff in seconds
    default: "10"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
